tenants:
  datasources:
    tenant1:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/base_adapter_db_tenant1
      username: root
      password: Sysadmin1234$
    tenant2:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/base_adapter_db_tenant2
      username: root
      password: Sysadmin1234$

